/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthReportesRouteImport } from './routes/_auth/reportes'
import { Route as AuthPublicarRouteImport } from './routes/_auth/publicar'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthGestionarUsuariosRouteImport } from './routes/_auth/gestionar-usuarios'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as PublicPublicacionIdRouteImport } from './routes/_public/publicacion.$id'
import { Route as AuthDashboardInmueblesRouteImport } from './routes/_auth/dashboard/inmuebles'
import { Route as AuthDashboardContratosRouteImport } from './routes/_auth/dashboard/contratos'
import { Route as AuthDashboardClientesRouteImport } from './routes/_auth/dashboard/clientes'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportesRoute = AuthReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPublicarRoute = AuthPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGestionarUsuariosRoute = AuthGestionarUsuariosRouteImport.update({
  id: '/gestionar-usuarios',
  path: '/gestionar-usuarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const PublicPublicacionIdRoute = PublicPublicacionIdRouteImport.update({
  id: '/publicacion/$id',
  path: '/publicacion/$id',
  getParentRoute: () => PublicRoute,
} as any)
const AuthDashboardInmueblesRoute = AuthDashboardInmueblesRouteImport.update({
  id: '/inmuebles',
  path: '/inmuebles',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardContratosRoute = AuthDashboardContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardClientesRoute = AuthDashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/gestionar-usuarios': typeof AuthGestionarUsuariosRoute
  '/profile': typeof AuthProfileRoute
  '/publicar': typeof AuthPublicarRoute
  '/reportes': typeof AuthReportesRoute
  '/settings': typeof AuthSettingsRoute
  '/faq': typeof PublicFaqRoute
  '/dashboard/clientes': typeof AuthDashboardClientesRoute
  '/dashboard/contratos': typeof AuthDashboardContratosRoute
  '/dashboard/inmuebles': typeof AuthDashboardInmueblesRoute
  '/publicacion/$id': typeof PublicPublicacionIdRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof PublicIndexRoute
  '/gestionar-usuarios': typeof AuthGestionarUsuariosRoute
  '/profile': typeof AuthProfileRoute
  '/publicar': typeof AuthPublicarRoute
  '/reportes': typeof AuthReportesRoute
  '/settings': typeof AuthSettingsRoute
  '/faq': typeof PublicFaqRoute
  '/dashboard/clientes': typeof AuthDashboardClientesRoute
  '/dashboard/contratos': typeof AuthDashboardContratosRoute
  '/dashboard/inmuebles': typeof AuthDashboardInmueblesRoute
  '/publicacion/$id': typeof PublicPublicacionIdRoute
  '/dashboard': typeof AuthDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/gestionar-usuarios': typeof AuthGestionarUsuariosRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/publicar': typeof AuthPublicarRoute
  '/_auth/reportes': typeof AuthReportesRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/dashboard/clientes': typeof AuthDashboardClientesRoute
  '/_auth/dashboard/contratos': typeof AuthDashboardContratosRoute
  '/_auth/dashboard/inmuebles': typeof AuthDashboardInmueblesRoute
  '/_public/publicacion/$id': typeof PublicPublicacionIdRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/dashboard'
    | '/gestionar-usuarios'
    | '/profile'
    | '/publicar'
    | '/reportes'
    | '/settings'
    | '/faq'
    | '/dashboard/clientes'
    | '/dashboard/contratos'
    | '/dashboard/inmuebles'
    | '/publicacion/$id'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/gestionar-usuarios'
    | '/profile'
    | '/publicar'
    | '/reportes'
    | '/settings'
    | '/faq'
    | '/dashboard/clientes'
    | '/dashboard/contratos'
    | '/dashboard/inmuebles'
    | '/publicacion/$id'
    | '/dashboard'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_public'
    | '/_auth/dashboard'
    | '/_auth/gestionar-usuarios'
    | '/_auth/profile'
    | '/_auth/publicar'
    | '/_auth/reportes'
    | '/_auth/settings'
    | '/_public/faq'
    | '/_public/'
    | '/_auth/dashboard/clientes'
    | '/_auth/dashboard/contratos'
    | '/_auth/dashboard/inmuebles'
    | '/_public/publicacion/$id'
    | '/_auth/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reportes': {
      id: '/_auth/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthReportesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/publicar': {
      id: '/_auth/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AuthPublicarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gestionar-usuarios': {
      id: '/_auth/gestionar-usuarios'
      path: '/gestionar-usuarios'
      fullPath: '/gestionar-usuarios'
      preLoaderRoute: typeof AuthGestionarUsuariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_public/publicacion/$id': {
      id: '/_public/publicacion/$id'
      path: '/publicacion/$id'
      fullPath: '/publicacion/$id'
      preLoaderRoute: typeof PublicPublicacionIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/dashboard/inmuebles': {
      id: '/_auth/dashboard/inmuebles'
      path: '/inmuebles'
      fullPath: '/dashboard/inmuebles'
      preLoaderRoute: typeof AuthDashboardInmueblesRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/contratos': {
      id: '/_auth/dashboard/contratos'
      path: '/contratos'
      fullPath: '/dashboard/contratos'
      preLoaderRoute: typeof AuthDashboardContratosRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/clientes': {
      id: '/_auth/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof AuthDashboardClientesRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
  }
}

interface AuthDashboardRouteChildren {
  AuthDashboardClientesRoute: typeof AuthDashboardClientesRoute
  AuthDashboardContratosRoute: typeof AuthDashboardContratosRoute
  AuthDashboardInmueblesRoute: typeof AuthDashboardInmueblesRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardClientesRoute: AuthDashboardClientesRoute,
  AuthDashboardContratosRoute: AuthDashboardContratosRoute,
  AuthDashboardInmueblesRoute: AuthDashboardInmueblesRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
  AuthGestionarUsuariosRoute: typeof AuthGestionarUsuariosRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthPublicarRoute: typeof AuthPublicarRoute
  AuthReportesRoute: typeof AuthReportesRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
  AuthGestionarUsuariosRoute: AuthGestionarUsuariosRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthPublicarRoute: AuthPublicarRoute,
  AuthReportesRoute: AuthReportesRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicFaqRoute: typeof PublicFaqRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPublicacionIdRoute: typeof PublicPublicacionIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFaqRoute: PublicFaqRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPublicacionIdRoute: PublicPublicacionIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
